DEF NUM_PLAYER_NAMES EQU 3

DEF PLAYERNAME1 EQUS "BLUE"
DEF PLAYERNAME2 EQUS "KASSIM"
DEF PLAYERNAME3 EQUS "JULIEN"

DEF RIVALNAME1 EQUS "RED"
DEF RIVALNAME2 EQUS "GREEN"
DEF RIVALNAME3 EQUS "RICHIE"

